global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ti-garantias-dev-backend
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["tigarantias-dev-fe.mangobay-9146375d.centralus.azurecontainerapps.io:443"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
